spring.application.name=asset-tracking-system

spring.datasource.url=jdbc:mysql://localhost:3306/asset_tracking_db
spring.datasource.username=root
spring.datasource.password=mprathamsql1810

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
